// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Azure_Upload_file_Core.Entities;
using System;
using System.Collections.Generic;

namespace Azure_Upload_file_Entities.Concrete.DatabaseFirst
{
    public partial class InfoFiles:IEntity
    {
        public int IdFile { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FileSize { get; set; }
    }
}